version: "3.9"
volumes: 
  ...
networks: 
  ...
services:
  db:                            # название сервиса 
    image: postgres:alpine       # Образ, который необходимо запустить. 
    restart: unless-stopped      # Необязательный параметр. Политика перезапуска, то есть правила, до каких пор надо перезапускать контейнер. Перезапуск может потребоваться, если, например, наш контейнер упал из-за ошибки. 
    networks:                    # Необязательный параметр. Список сетей для контейнера - здесь указываем сети из секции networks. 
      - backend 
    volumes:                     # Необязательный параметр. Здесь указываем volume из секции volumes или монтируем напрямую в хостовую систему 
      - pgdata:/var/lib/postgresql/data
      - ./logs:/var/log
    depends_on:                  # Необязательный параметр. От каких сервисов зависим, то есть текущий сервис не запустится, пока не запустятся указанные здесь сервисы 
      - redis 
    ports:                       # Необязательный параметр. Указываем проброс портов. 
      - "5432:5432" 
    env_file:                    # Необязательный параметр. Указываем файлы с переменными окружения для контейнера. 
      - .env 